# Generated by Django 3.1.3 on 2020-11-24 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='isAnswer',
            field=models.BooleanField(default=False),
        ),
    ]
