# Generated by Django 3.1.2 on 2020-11-26 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WordBullet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bullet', models.CharField(max_length=128)),
                ('typeface', models.CharField(default='宋体', max_length=64)),
                ('color', models.CharField(default='#000000', max_length=16)),
                ('type', models.IntegerField(choices=[(0, 'common'), (1, 'advanced')], default='common')),
                ('size', models.CharField(default=16, max_length=2)),
            ],
            options={
                'verbose_name': '弹幕信息',
                'verbose_name_plural': '弹幕信息',
                'db_table': 'wordbullet_table',
            },
        ),
    ]
